modified:   .githooks/pre-push

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -1,14 +1,21 @@
 #!/bin/sh
 # Push content subrepo before pushing main repo
 
-remote="$1"
-
-. "$(pwd)/.env"
-if [ "$SKIP_TESTS" = "true" ]; then
+if [ -n "$SKIP_PRE_PUSH" ]; then
+  echo "Skipping pre-push"
   exit 0
 fi
 
-set -eu
+remote="$1"
+
+. "$(pwd)/.env"
+
+if [ "$SKIP_TESTS" = "true" ]; then
+  echo "Skipping tests"
+  exit 0
+fi
+
+set -e
 set -x
 
 read_branches() {
@@ -19,14 +26,14 @@ read_branches() {
   while IFS=' ' read -r _ _ remote_ref _; do
     seen_refs=true
     case "$remote_ref" in
-      refs/heads/testing|refs/heads/staging|refs/heads/main|refs/heads/production)
-        echo "Matched deployable branch: ${remote_ref#refs/heads/}"
-        matched=true
-        # Continue reading all refs; do not exit here to process all
-        ;;
-      *)
-        echo "Non-deployable branch: ${remote_ref#refs/heads/}"
-        ;;
+    refs/heads/testing | refs/heads/staging | refs/heads/main | refs/heads/production)
+      echo "Matched deployable branch: ${remote_ref#refs/heads/}"
+      matched=true
+      # Continue reading all refs; do not exit here to process all
+      ;;
+    *)
+      echo "Non-deployable branch: ${remote_ref#refs/heads/}"
+      ;;
     esac
   done <<EOF
 $hook_input
@@ -64,21 +71,20 @@ else
   read_branches || read_branches_result=$?
 fi
 
-
 case "$read_branches_result" in
-  0)
-    COMMIT_HASH=$(git rev-parse HEAD)
-    if ! ./scripts/pre-push-tests.sh "$COMMIT_HASH"; then
-      echo "Tests failed. Aborting push."
-      exit 1
-    fi
-    ;;
-  1)
-    echo "Skipping tests: no deployable branches pushed."
-    ;;
-  2)
-    echo "No refs detected. Possibly a dry push or no changes."
-    ;;
+0)
+  COMMIT_HASH=$(git rev-parse HEAD)
+  if ! ./scripts/pre-push-tests.sh "$COMMIT_HASH"; then
+    echo "Tests failed. Aborting push."
+    exit 1
+  fi
+  ;;
+1)
+  echo "Skipping tests: no deployable branches pushed."
+  ;;
+2)
+  echo "No refs detected. Possibly a dry push or no changes."
+  ;;
 esac
 
 cd content
